#ifndef MANDEL_VERSION_H
#define MANDEL_VERSION_H

#define MANDEL_VERSION_MAJOR 1
#define MANDEL_VERSION_MINOR 4
#define MANDEL_VERSION_PATCH 0
#define MANDEL_VERSION_BUILD 0

#define MANDEL_VERSION_COMMA 1, 4, 0, 0
#define MANDEL_VERSION_STRING "1.4.0"

#endif
